language: ruby


matrix:
  include:
  - rvm: 1.9.3
    gemfile: gemfiles/Gemfile.rails-3.2.x
  - rvm: 1.9.3
    gemfile: Gemfile
  - rvm: 2.0.0
    gemfile: Gemfile
  - rvm: 2.1
    gemfile: Gemfile
  - rvm: 2.2
    gemfile: Gemfile
  - rvm: 2.6
    gemfile: Gemfile

script: bundle exec rake db:migrate RAILS_ENV=test && bundle exec rspec spec